apiVersion: v2
name: tarot-as-a-service
description: A Helm chart for Tarot-as-a-Service API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - tarot
  - api
  - llm
  - openrouter
maintainers:
  - name: randomtoy
